### ISSUE TITLE
Reformat Opportunities page

### ISSUE THREAD

**Issue by patrickjwoods** [orbit-love/orbit-model#10]
Redesign [Opportunities](https://github.com/orbit-love/orbit-model/blob/master/opportunities.md#opportunities) to group by event, reward, recognition, etc.

**Comment by malgamves** [comment]
Happy to jump onto this 🌠

**Comment by dzello** [comment]
@malgamves Cool, go for it! Happy to review or talk through it.

**Comment by dzello** [comment]
Done via #18
