### ISSUE TITLE
Add section about downloading slack icons

### ISSUE THREAD

**Issue by dzello** [orbit-love/orbit-model#17]
https://orbit.love/blog/download-these-orbit-model-icons-for-your-slack-workspace

**Comment by patrickjwoods** [comment]
@dzello Where do you think this should go? Maybe in a new "Resources" section?

**Comment by dzello** [comment]
@patrickjwoods Yeah that'd work!

**Comment by dzello** [comment]
@alexlsalt Can you help us out and find a home for the Orbit model chat icons in the README?
