### ISSUE TITLE
Reach Tiers

### ISSUE THREAD

**Issue by krhoyt** [orbit-love/orbit-model#22]
What happens when there are multiple tiers of "reach"? In the given example, what if "1k Twitter Followers" is worth "1" and "2k Twitter Followers" is worth "2" and Avery has 3k followers? Does she then get both reach values (for a total of 3), or just the higher (2)?

My gut says - whatever, so long as it is consistently applied - but then I worry about it skewing gravity. Can the model write-up be updated to clarify this situation?

**Comment by dzello** [comment]
Good question there, thanks for opening the issue.

I would probably model that situation with several ranges for the following count, each a the different reach value. For example:

- 1-2k followers: +1
- 2-5k followers: +2
- 5+k followers: +3

Each member would only get values for the range they're in, not the ranges that came before it. What do you think about that?

**Comment by krhoyt** [comment]
Ranges seem to show up frequently in the Orbit model, so I think your suggestion fits. It also clarifies (for me) the question around cumulative scoring. This could probably be made clear in the document by just adding another Twitter row to the "Reach element/Score" table.

**Comment by dzello** [comment]
Thanks again for this one @krhoyt!
