### ISSUE TITLE
Redefining 'love' as the sum of the activity scores

### ISSUE THREAD

**Issue by albert0marti** [orbit-love/orbit-model#26]
Given that "_the **maximum** tells us the largest contribution the member has made, and the **sum** gives us a picture of their overall participation level_", wouldn't it be more accurate to use the **sum**  to measure someone's engagement / love?

**Comment by dzello** [comment]
Hi @albert0marti, thanks for starting the discussion here. Sum vs. maximum for love is something we have debated over, and I think the time is good to look at it again with what we've learned about using the model in practice over the last few months. Give me a minute to think about it and then I'd like to continue the discussion.

**Comment by dzello** [comment]
Closing as superceded by later discussions e.g. #29.
