### ISSUE TITLE
The symbol ^ in algorithm of "love" means  "xor", or "power"  in math

### ISSUE THREAD

**Issue by robekeane** [orbit-love/orbit-model#36]
Does anyone know the symbol ^ in algorithm of "love" means  "xor", or "power"  in math ? I really got confused! Thanks!

**Comment by phacks** [comment]
Hi @robekeane! Thanks for asking. It means “power” in that context.

**Comment by robekeane** [comment]
> Hi @robekeane! Thanks for asking. It means “power” in that context.

@phacks Thanks!
