### ISSUE TITLE
B&W canvas for printing?

### ISSUE THREAD

**Issue by waigani** [orbit-love/orbit-model#45]
Keen to print this out the canvas at the office, but dread the amount of ink it would take. 

A B&W line art version would be great.

**Comment by dzello** [comment]
@waigani Great idea, thanks for suggesting. I've asked one of our design-inclined folks to put this together and I'll post it here once it's ready.

**Comment by alexlsalt** [comment]
Hey there, @waigani ! We've just added a b&w version of our Orbit Model canvas to this readme! 

You can find [it right here](https://github.com/orbit-love/orbit-model#orbit-model-printables).

Thanks again for this great suggestion! 😄
