### ISSUE TITLE
option to import new members 

### ISSUE THREAD

**Issue by yuval-hazaz** [orbit-love/orbit-model#48]
An option to import new member from json, CSV, Excel, or other types can be very helpful

**Comment by guillaumemillot** [comment]
Hi Yuval, it's coming very soon! (likely this week)

**Comment by guillaumemillot** [comment]
Good news as we actually just deployed the feature! We're looking for a couple of beta users.
Is that a feature that you would like to try?

**Comment by yuval-hazaz** [comment]
> Good news as we actually just deployed the feature! We're looking for a couple of beta users.
> Is that a feature that you would like to try?

sure, I would love to

**Comment by guillaumemillot** [comment]
Great, closing the issue in favor of Discord!

**Comment by gjsherry** [comment]
In case anyone is following up, now available: https://docs.orbit.love/docs#add-members-to-your-workspace-via-csv
