### ISSUE TITLE
similar project: alchi, construction of extended families

### ISSUE THREAD

**Issue by milahu** [orbit-love/orbit-model#55]
so youre modeling human relations like in the macrocosmos ... planets in random locations, each with their gravity field
but i prefer to see us humans as "mesocosmos" beings, where such over-simple rules give poor results

i made a thesis on: how we must combine different types of people, so they all can be happy

... also without machines : )
similar to albert einstein's metric "if you cant explain it to a six year old, then you dont understand it yourself"
i have the metric "if a system does not work nude, then it is a bad system."
"nude" as in: no tools, no machines, no electricity, no calculators, no data stores, no pen and paper, etc. etc.

let me just copy-paste [my reddit comment](https://www.reddit.com/r/preppers/comments/lc32m2/given_that_during_a_collapse_or_emergency_people/gzq8dwb/?utm_source=reddit&utm_medium=web2x&context=3), since i need to get this out to a hundred people, to get one positive response ... aka "the hustlers method"

>most all the ways people used to form tight communities a few decades ago have been blown into dust. Its a societal level problem that can't be fixed by just beating the drum, but that doesn't mean we shouldn't try.

im trying to solve this problem in my book [pallas - construction of extended families](https://milahu.github.io/alchi/src/alchi-book/build/). i make exact predictions on [how we must combine](https://milahu.github.io/alchi/src/alchi-maps/dist/alchi-maps.2020-09-02.html) different [types of people](https://milahu.github.io/alchi/english/alchi-tables.html), so they all can be happy. the book is about 80% finished and i need more aggressive advertisement, since our time is running fast - i say 6 months to shtf. i have zero hope for my own survival, but maybe my ideas can survive, if they are "fit" enough to survive.

**Comment by phazonoverload** [comment]
We use the issues in this GitHub repository to track the development of the Orbit Model itself. As this is more of a side discussion, I'm going to close this issue.
